### ISSUE TITLE
List of new features

### ISSUE THREAD

**Issue by sisskind** [sisskind/spark-map#51]
@Joshua106728 @bentneb9 @SlpyBkWrm @Masonnunya 

What features are missing from the map? Should the user be able to add multiple layers to the map? Add to the list!

- [ ] Check incoming Overpass queries to make sure they are valid
- [ ] Make sure coordinates are valid
- [ ] Allow users to search for a place to bring them there (i.e., "Bring me to Washington, DC")
- [ ] Custom colors for layers

**Comment by SlpyBkWrm** [comment]
- [ ] - Suggestions from Ellie, Mason, and Caden. Add Identifiers to the popups. ex: "you've clicked on 'The Leaky Cauldron'" like so? And when you click on a road it tells you which road and so on. 
- [ ] - A popup on the screen that tells you when the query is done running.
- [ ] - Another thing I noticed is that in order to see the queries you have to manually go into the layers section to select them before they show, perhaps there is a way to make that process automatic instead?
- [ ] - Maybe something to prevent overlapping queries? ie: no overlapping colors
- [ ] - Also in the layers if there was an indicator of what color everything is? like a red square or dot next to an oways layer for example. 
- [ ] - Is there a way to add labels to the ersi layer map? It would be dead useful to be able to navigate a bit smoother with road labels.
more to be added

**Comment by SlpyBkWrm** [comment]
petition to change default highways style to cornflower blue #6495ED
